

class HouseItem {
  String name;
  String location;
  double distance;
  String image;
  int nBed;
  int nBath;
  String kitchen;
  String livingRoom;
  String bathRoom;
  String bedRoom;
  String diningRoom;
  String pool;
  String owner;
  String ownerImage;
  int price;
  String description;
  String map;

  HouseItem({
    required this.name,
    required this.location,
    required this.distance,
    required this.image,
    required this.nBed,
    required this.nBath,
    required this.kitchen,
    required this.livingRoom,
    required this.bathRoom,
    required this.bedRoom,
    required this.diningRoom,
    required this.pool,
    required this.owner,
    required this.ownerImage,
    required this.price,
    required this.description,
    required this.map,
});
}

final List<HouseItem> nearHouses = [
  HouseItem(
    name: 'Dreamsville House',
    location: 'JL Sultan Iskandar Muda',
    distance: 1.8,
    image: 'assets/images/houses/house_01.jpg',
    nBed: 6,
    nBath: 4,
    kitchen: 'assets/images/houses/kitchen.jpg',
    livingRoom: 'assets/images/houses/living_room.jpg',
    bathRoom: 'assets/images/houses/bath_room.jpg',
    bedRoom: 'assets/images/houses/bed_room.jpg',
    diningRoom: 'assets/images/houses/dining_room.jpg',
    pool: 'assets/images/houses/swimming_pool.jpg',
    owner: 'Magnus Weston',
    ownerImage: 'assets/images/owners/2.jpg',
    price: 2500000000000,
    description: 'The 3 level house that has a modern design has a large pool and a garage that fits up to four cars.',
    map: 'assets/images/houses/map1.jpg',
  ),
  HouseItem(
    name: 'Hampton Lovely',
    location: 'California Street 18',
    distance: 2.7,
    image: 'assets/images/houses/house_09.jpeg',
    nBed: 11,
    nBath: 7,
    kitchen: 'assets/images/houses/kitchen.jpg',
    livingRoom: 'assets/images/houses/living_room3.jpg',
    bathRoom: 'assets/images/houses/bath_room.jpg',
    bedRoom: 'assets/images/houses/bed_room4.jpg',
    diningRoom: 'assets/images/houses/dining_room.jpg',
    pool: 'assets/images/houses/swimming_pool.jpg',
    owner: 'Sr Von Richard',
    ownerImage: 'assets/images/owners/4.jpg',
    price: 4000000000000,
    description: 'The 5 level house that has a modern design has a large pool and a garage that fits up to seven cars.',
    map: 'assets/images/houses/map1.jpg',
  ),
  HouseItem(
    name: 'Perchault Rivers',
    location: 'Mutant Liverain',
    distance: 2.4,
    image: 'assets/images/houses/house_11.jpeg',
    nBed: 8,
    nBath: 5,
    kitchen: 'assets/images/houses/kitchen.jpg',
    livingRoom: 'assets/images/houses/living_room.jpg',
    bathRoom: 'assets/images/houses/bath_room.jpg',
    bedRoom: 'assets/images/houses/bed_room.jpg',
    diningRoom: 'assets/images/houses/dining_room.jpg',
    pool: 'assets/images/houses/swimming_pool.jpg',
    owner: 'Rachelle Storn',
    ownerImage: 'assets/images/owners/5.jpg',
    price: 2800000000000,
    description: 'The 4 level house that has a modern design has a large pool and a garage that fits up to five cars.',
    map: 'assets/images/houses/map1.jpg',
  ),
  HouseItem(
    name: 'Quietly Storm',
    location: 'Leverage Town',
    distance: 3.1,
    image: 'assets/images/houses/house_14.jpg',
    nBed: 7,
    nBath: 3,
    kitchen: 'assets/images/houses/kitchen.jpg',
    livingRoom: 'assets/images/houses/living_room.jpg',
    bathRoom: 'assets/images/houses/bath_room.jpg',
    bedRoom: 'assets/images/houses/bed_room.jpg',
    diningRoom: 'assets/images/houses/dining_room.jpg',
    pool: 'assets/images/houses/swimming_pool.jpg',
    owner: 'Travis Lockland',
    ownerImage: 'assets/images/owners/8.jpg',
    price: 2100000000000,
    description: 'The 3 level house that has a modern design has a large pool and a garage that fits up to three cars.',
    map: 'assets/images/houses/map1.jpg',
  ),
  HouseItem(
    name: 'Homelovely Being',
    location: 'Camicale Wear',
    distance: 1.4,
    image: 'assets/images/houses/house_12.jpg',
    nBed: 5,
    nBath: 3,
    kitchen: 'assets/images/houses/kitchen.jpg',
    livingRoom: 'assets/images/houses/living_room.jpg',
    bathRoom: 'assets/images/houses/bath_room.jpg',
    bedRoom: 'assets/images/houses/bed_room.jpg',
    diningRoom: 'assets/images/houses/dining_room.jpg',
    pool: 'assets/images/houses/swimming_pool.jpg',
    owner: 'Viviane Brent',
    ownerImage: 'assets/images/owners/1.jpg',
    price: 1900000000000,
    description: 'The 3.5 level house that has a modern design has a large pool and a garage that fits up to four cars.',
    map: 'assets/images/houses/map1.jpg',
  ),
  HouseItem(
    name: 'GeorgesVille Suit',
    location: 'Berkshire Place',
    distance: 0.9,
    image: 'assets/images/houses/house_10.jpg',
    nBed: 6,
    nBath: 4,
    kitchen: 'assets/images/houses/kitchen.jpg',
    livingRoom: 'assets/images/houses/living_room.jpg',
    bathRoom: 'assets/images/houses/bath_room.jpg',
    bedRoom: 'assets/images/houses/bed_room.jpg',
    diningRoom: 'assets/images/houses/dining_room.jpg',
    pool: 'assets/images/houses/swimming_pool.jpg',
    owner: 'Elvis Nimway',
    ownerImage: 'assets/images/owners/6.jpg',
    price: 1500000000000,
    description: 'The 3 level house that has a modern design has a large pool and a garage that fits up to four cars.',
    map: 'assets/images/houses/map1.jpg',
  ),
  HouseItem(
    name: 'Gallagher Frime',
    location: 'Pooltown Blood',
    distance: 3.5,
    image: 'assets/images/houses/house_08.jpg',
    nBed: 6,
    nBath: 4,
    kitchen: 'assets/images/houses/kitchen.jpg',
    livingRoom: 'assets/images/houses/living_room.jpg',
    bathRoom: 'assets/images/houses/bath_room.jpg',
    bedRoom: 'assets/images/houses/bed_room.jpg',
    diningRoom: 'assets/images/houses/dining_room.jpg',
    pool: 'assets/images/houses/swimming_pool.jpg',
    owner: 'Nicole Lance',
    ownerImage: 'assets/images/owners/7.jpg',
    price: 1600000000000,
    description: 'The 3 level house that has a modern design has a large pool and a garage that fits up to four cars.',
    map: 'assets/images/houses/map1.jpg',
  ),
];

final List<HouseItem> bestHouses = [
  HouseItem(
    name: 'Yorkshire Real',
    location: 'Lilian Street',
    distance: 1.8,
    image: 'assets/images/houses/house_02.jpg',
    nBed: 6,
    nBath: 4,
    kitchen: 'assets/images/houses/kitchen.jpg',
    livingRoom: 'assets/images/houses/living_room.jpg',
    bathRoom: 'assets/images/houses/bath_room.jpg',
    bedRoom: 'assets/images/houses/bed_room.jpg',
    diningRoom: 'assets/images/houses/dining_room.jpg',
    pool: 'assets/images/houses/swimming_pool.jpg',
    owner: 'Magnus Weston',
    ownerImage: 'assets/images/owners/2.jpg',
    price: 2500000000000,
    description: 'The 3 level house that has a modern design has a large pool and a garage that fits up to four cars.',
    map: 'assets/images/houses/map1.jpg',
  ),
  HouseItem(
    name: 'Dreamsville House',
    location: 'JL Sultan Iskandar Muda',
    distance: 1.8,
    image: 'assets/images/houses/house_03.jpg',
    nBed: 6,
    nBath: 4,
    kitchen: 'assets/images/houses/kitchen.jpg',
    livingRoom: 'assets/images/houses/living_room.jpg',
    bathRoom: 'assets/images/houses/bath_room.jpg',
    bedRoom: 'assets/images/houses/bed_room.jpg',
    diningRoom: 'assets/images/houses/dining_room.jpg',
    pool: 'assets/images/houses/swimming_pool.jpg',
    owner: 'Magnus Weston',
    ownerImage: 'assets/images/owners/2.jpg',
    price: 2000000000000,
    description: 'The 3 level house that has a modern design has a large pool and a garage that fits up to four cars.',
    map: 'assets/images/houses/map1.jpg',
  ),
  HouseItem(
    name: 'Dreamsville House',
    location: 'JL Sultan Iskandar Muda',
    distance: 1.8,
    image: 'assets/images/houses/house_04.jpg',
    nBed: 6,
    nBath: 4,
    kitchen: 'assets/images/houses/kitchen.jpg',
    livingRoom: 'assets/images/houses/living_room.jpg',
    bathRoom: 'assets/images/houses/bath_room.jpg',
    bedRoom: 'assets/images/houses/bed_room.jpg',
    diningRoom: 'assets/images/houses/dining_room.jpg',
    pool: 'assets/images/houses/swimming_pool.jpg',
    owner: 'Magnus Weston',
    ownerImage: 'assets/images/owners/2.jpg',
    price: 1500000000000,
    description: 'The 3 level house that has a modern design has a large pool and a garage that fits up to four cars.',
    map: 'assets/images/houses/map1.jpg',
  ),
  HouseItem(
    name: 'Dreamsville House',
    location: 'JL Sultan Iskandar Muda',
    distance: 1.8,
    image: 'assets/images/houses/house_05.jpg',
    nBed: 6,
    nBath: 4,
    kitchen: 'assets/images/houses/kitchen.jpg',
    livingRoom: 'assets/images/houses/living_room.jpg',
    bathRoom: 'assets/images/houses/bath_room.jpg',
    bedRoom: 'assets/images/houses/bed_room.jpg',
    diningRoom: 'assets/images/houses/dining_room.jpg',
    pool: 'assets/images/houses/swimming_pool.jpg',
    owner: 'Magnus Weston',
    ownerImage: 'assets/images/owners/2.jpg',
    price: 1500000000000,
    description: 'The 3 level house that has a modern design has a large pool and a garage that fits up to four cars.',
    map: 'assets/images/houses/map1.jpg',
  ),
  HouseItem(
    name: 'Dreamsville House',
    location: 'JL Sultan Iskandar Muda',
    distance: 1.8,
    image: 'assets/images/houses/house_06.jpg',
    nBed: 6,
    nBath: 4,
    kitchen: 'assets/images/houses/kitchen.jpg',
    livingRoom: 'assets/images/houses/living_room.jpg',
    bathRoom: 'assets/images/houses/bath_room.jpg',
    bedRoom: 'assets/images/houses/bed_room.jpg',
    diningRoom: 'assets/images/houses/dining_room.jpg',
    pool: 'assets/images/houses/swimming_pool.jpg',
    owner: 'Magnus Weston',
    ownerImage: 'assets/images/owners/2.jpg',
    price: 1500000000000,
    description: 'The 3 level house that has a modern design has a large pool and a garage that fits up to four cars.',
    map: 'assets/images/houses/map1.jpg',
  ),
  HouseItem(
    name: 'Dreamsville House',
    location: 'JL Sultan Iskandar Muda',
    distance: 1.8,
    image: 'assets/images/houses/house_07.jpg',
    nBed: 6,
    nBath: 4,
    kitchen: 'assets/images/houses/kitchen.jpg',
    livingRoom: 'assets/images/houses/living_room.jpg',
    bathRoom: 'assets/images/houses/bath_room.jpg',
    bedRoom: 'assets/images/houses/bed_room.jpg',
    diningRoom: 'assets/images/houses/dining_room.jpg',
    pool: 'assets/images/houses/swimming_pool.jpg',
    owner: 'Magnus Weston',
    ownerImage: 'assets/images/owners/2.jpg',
    price: 1500000000000,
    description: 'The 3 level house that has a modern design has a large pool and a garage that fits up to four cars.',
    map: 'assets/images/houses/map1.jpg',
  ),
  HouseItem(
    name: 'Dreamsville House',
    location: 'JL Sultan Iskandar Muda',
    distance: 1.8,
    image: 'assets/images/houses/house_13.jpg',
    nBed: 6,
    nBath: 4,
    kitchen: 'assets/images/houses/kitchen.jpg',
    livingRoom: 'assets/images/houses/living_room.jpg',
    bathRoom: 'assets/images/houses/bath_room.jpg',
    bedRoom: 'assets/images/houses/bed_room.jpg',
    diningRoom: 'assets/images/houses/dining_room.jpg',
    pool: 'assets/images/houses/swimming_pool.jpg',
    owner: 'Magnus Weston',
    ownerImage: 'assets/images/owners/2.jpg',
    price: 1500000000000,
    description: 'The 3 level house that has a modern design has a large pool and a garage that fits up to four cars.',
    map: 'assets/images/houses/map1.jpg',
  ),
];